import type { Config } from "tailwindcss";

export default {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-high": "#e7e7f3",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dce2f3",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "surface-container-low": "#f3f3fe",
        secondary: "#585f6c",
        "on-tertiary": "#ffffff",
        surface: "#faf8ff",
        "primary-fixed": "#dbe1ff",
        "on-secondary-fixed-variant": "#404754",
        "on-surface": "#191b23",
        "on-primary-container": "#eeefff",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#e1e2ed",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        "on-primary-fixed": "#00174b",
        "surface-container": "#ededf9",
        "secondary-container": "#dce2f3",
        "surface-container-highest": "#e1e2ed",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3039",
        "on-secondary-fixed": "#151c27",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-container": "#5e6572",
        "surface-bright": "#faf8ff",
        tertiary: "#006242",
        "on-tertiary-fixed": "#002113",
        error: "#ba1a1a",
        "surface-dim": "#d9d9e5",
        "tertiary-container": "#007d55",
        primary: "#004ac6",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2563eb",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#f0f0fb",
        "on-background": "#191b23",
        "on-tertiary-container": "#bdffdb",
        "secondary-fixed-dim": "#c0c7d6",
        "primary-fixed-dim": "#b4c5ff",
        outline: "#737686",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        background: "#faf8ff",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
